force-app/main/default/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <description>This will allow end-users to store the Bank Accounts data.</description>
    <label>Bank Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BankAccount__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <defaultValue>10000</defaultValue>
    <description>Stores the amount the bank account has.</description>
    <inlineHelpText>Amount in the bank account.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/QueueableAC1.cls
//QueueableAC1.apxc
global class QueueableAC1 implements Queueable{
    BankAccount__c bank;
    public QueueableAC1(BankAccount__c bank){ this.bank = bank; }
    global void execute(QueueableContext qc){
        insert bank;
        executeQueueableAC2();
    }
    global void executeQueueableAC2(){
        System.enqueueJob(new QueueableAC2(bank));
    }
}


// //Anonymous Window (Start Queueable Chain):
// BankAccount__c bank = new BankAccount__c(Name='Deepak', amount__c=400000);
// System.enqueueJob(new QueueableAC1(bank));